# This pubspec.yaml file is part of the 'engaige_meal_tracker_demo' Flutter project.
# This project serves as a demo to showcase programming skills for a potential employer.

name: engaige_meal_tracker_demo
description: "Demo project to assess programming skills, including state management, database interaction, localization, and user authentication."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Application versioning (using semantic versioning: MAJOR.MINOR.PATCH+BUILD).
version: 1.0.0+1

# Flutter SDK and Dart environment settings
environment:
  sdk: ^3.5.3

# Dependencies for the project
dependencies:
  flutter:
    sdk: flutter

  ## Localization (translations)
  # Easy integration for multiple languages and locale support.
  easy_localization: ^3.0.1

  ## Authentication and API connection
  # Provides a prebuilt login screen and authentication flow.
  flutter_login: ^5.0.0
  # Enables HTTP calls to RESTful APIs (used for web-based API connections).
  http: ^1.2.2
  # For cryptography, such as hashing user passwords and securing sensitive data.
  crypto: ^3.0.2

  ## Local database.
  # Allows saving structured data locally on the device (SQLite).
  sqflite: ^2.2.2
  # Provides utilities to manipulate and build file system paths in a platform-independent way.
  path: ^1.8.3

  ## Shared preferences for simple key-value data storage
  # Persistent key-value storage for user preferences, lightweight local data storage.
  shared_preferences: ^2.0.15

  ## Icons
  # A collection of iOS-style icons for Cupertino design widgets.
  cupertino_icons: ^1.0.8

  ## State management
  # A widely used state management solution that decouples logic from the UI.
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Provides lint rules and best practices for Dart and Flutter development.
  flutter_lints: ^5.0.0

# Flutter-specific settings
flutter:

  # Ensure that Material Icons are included in the app for UI elements.
  uses-material-design: true

  # Asset configuration (for images and localization files).
  assets:
    - assets/images/
    - assets/images/flags/
    - assets/lang/

  # Optional fonts configuration (commented out as it's not needed currently).
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
